module.exports = [
  { id: 1, first_name: 'Georgena', last_name: 'Van der Baaren', email: 'gvanderbaaren0@netscape.com', typeIds: [1], skillsId: [45, 10, 25, 6], hour_rate: '$23.19', daily_capacity: 5 },
  { id: 2, first_name: 'Jorie', last_name: 'Margetson', email: 'jmargetson1@icq.com', typeIds: [2], skillsId: [4, 10, 25, 6], hour_rate: '$12.61', daily_capacity: 5 },
  { id: 3, first_name: 'Ellie', last_name: 'Grane', email: 'egrane2@ed.gov', typeIds: [1, 3], skillsId: [4, 10, 25, 15], hour_rate: '$31.20', daily_capacity: 4 },
  { id: 4, first_name: 'Cazzie', last_name: 'Goldes', email: 'cgoldes3@macromedia.com', typeIds: [3], skillsId: [4, 18, 25, 6], hour_rate: '$37.29', daily_capacity: 5 },
  { id: 5, first_name: 'Durand', last_name: 'Maslen', email: 'dmaslen4@ed.gov', typeIds: [2], skillsId: [4, 101, 25, 3], hour_rate: '$44.23', daily_capacity: 1 },
  { id: 6, first_name: 'Cayla', last_name: 'Lowde', email: 'clowde5@devhub.com', typeIds: [1, 2], skillsId: [4, 105, 25, 6], hour_rate: '$26.70', daily_capacity: 0 },
  { id: 7, first_name: 'Lydie', last_name: 'Wickes', email: 'lwickes6@e-recht24.de', typeIds: [2, 3], skillsId: [4, 10, 215, 6], hour_rate: '$2.21', daily_capacity: 5 },
  { id: 8, first_name: 'Hubie', last_name: 'Stiebler', email: 'hstiebler7@alibaba.com', typeIds: [3], skillsId: [4, 10, 25, 6], hour_rate: '$43.08', daily_capacity: 4 },
  { id: 9, first_name: 'Hunfredo', last_name: 'Longmate', email: 'hlongmate8@newsvine.com', typeIds: [1], skillsId: [4, 10, 25, 6], hour_rate: '$40.41', daily_capacity: 6 },
  { id: 10, first_name: 'Kerianne', last_name: 'Axston', email: 'kaxston9@pcworld.com', typeIds: [2], skillsId: [4, 10, 25, 6], hour_rate: '$23.99', daily_capacity: 5 },
  { id: 11, first_name: 'Micheline', last_name: 'Ropkes', email: 'mropkesa@jimdo.com', typeIds: [2, 3], skillsId: [4, 10, 25, 6], hour_rate: '$49.19', daily_capacity: 3 },
  { id: 12, first_name: 'Catharine', last_name: 'Clements', email: 'cclementsb@feedburner.com', typeIds: [1, 3], skillsId: [4, 10, 25, 6], hour_rate: '$48.99', daily_capacity: 8 },
  { id: 13, first_name: 'Gertrud', last_name: 'Betts', email: 'gbettsc@canalblog.com', typeIds: [1, 2], skillsId: [4, 10, 25, 6], hour_rate: '$35.13', daily_capacity: 8 },
  { id: 14, first_name: 'Haley', last_name: 'Philps', email: 'hphilpsd@clickbank.net', typeIds: [2, 3], skillsId: [4, 10, 25, 6], hour_rate: '$26.14', daily_capacity: 8 },
  { id: 15, first_name: 'Jewelle', last_name: 'Titchard', email: 'jtitcharde@cbsnews.com', typeIds: [2], skillsId: [4, 10, 25, 6], hour_rate: '$20.20', daily_capacity: 6 },
  { id: 16, first_name: 'Worthington', last_name: 'Duigan', email: 'wduiganf@sina.com.cn', typeIds: [1], skillsId: [4, 10, 25, 6], hour_rate: '$48.39', daily_capacity: 4 },
  { id: 17, first_name: 'Brittne', last_name: 'Keems', email: 'bkeemsg@imageshack.us', typeIds: [3], skillsId: [4, 10, 25, 6], hour_rate: '$42.06', daily_capacity: 7 },
  { id: 18, first_name: 'Alic', last_name: 'Swaden', email: 'aswadenh@blog.com', typeIds: [2, 3], skillsId: [4, 10, 25, 6], hour_rate: '$1.46', daily_capacity: 3 },
  { id: 19, first_name: 'Rupert', last_name: 'MacAndrew', email: 'rmacandrewi@amazon.com', typeIds: [1, 2], skillsId: [4, 10, 25, 6], hour_rate: '$8.81', daily_capacity: 4 },
  { id: 20, first_name: 'Marnia', last_name: 'Gaggen', email: 'mgaggenj@spiegel.de', typeIds: [1, 3], skillsId: [4, 10, 25, 6], hour_rate: '$22.37', daily_capacity: 5 }
];
